In [1]:
print('hello world')

hello world


In [1]:
x=4
x="sally"
print(x)

sally


In [2]:
a=(1,2,3,4,5)

In [12]:
print(a)

(1, 2, 3, 4, 5)


In [13]:
print('java')

java


In [14]:
print('rakesh')

rakesh


In [16]:
cs=(1,2,3,4)
print(cs)

(1, 2, 3, 4)


In [1]:
ab=(1,2,3,4,5)
print(ab)

(1, 2, 3, 4, 5)


In [2]:
print(ab)

(1, 2, 3, 4, 5)


In [20]:
print('rakesh',1,2,2,4)


rakesh 1 2 2 4


In [ ]:
print(1,2,3,4,)

# Creating variables

In [1]:
Age=6
print('My name is '  +  _name)
_name="Rakesh"


NameError: name '_name' is not defined

In [12]:
_age

6

In [13]:
_name

'Rakesh'

In [8]:
print(x)
print(y)

6
Rakesh


In [25]:
x=7
y="rakesh"
print(x)
print(y)

7
rakesh


In [26]:
x="orange"
y="grape"
z="pineapple"
print(x,y,z)

orange grape pineapple


In [35]:
x,y,z="rakesh","ram","raj"
print(x,y,z)
print(y)
print(z)

rakesh ram raj
ram
raj


In [36]:
x=y=z="rakesh"
print(x)
print(y)
print(z)

rakesh
rakesh
rakesh


In [4]:
x="awesome"
print("python is " + x)
print(x)

python is awesome
awesome


In [5]:
x="awesome"
print("python is" + x)
print(x)

python isawesome
awesome


In [6]:
x="awesome"
print("python is " + x)

python is awesome


In [7]:
x="awesome"
print("python is" + x)

python isawesome


In [44]:
x="rakesh"
print("python is " + x)

python is rakesh


In [7]:
x="python "
y="is my favourite "
print(x+y)

python is my favourite 


In [11]:
x=5
y=6
print(x+y)

11


In [48]:
x=8
y=10
print(x+y)

18


In [12]:
x=8
y="rakesh"
print(x)
print(y)

8
rakesh


In [17]:
name="awesome"
def myfunc():
    print("python is" + name)
myfunc()

python isawesome


In [64]:
x="awesome"
def myfunc():
    print("python is" + x)
myfunc()
    

python isawesome


In [65]:
x="awesome"
def myfunc():
    print("python is " + x)

myfunc()

python is awesome


In [66]:
x="awesome"
def myfunc():
    x="fantastic"
    print("python is " + x)
myfunc()
print("python is " + x)

python is fantastic
python is awesome


In [68]:
x="awesome"


def myfunc():
    x="fantastic"
    print("python is" + x)

myfunc()
    
print("python is " + x)

python isfantastic
python is awesome


In [77]:
x=1

def add_no():
    global x
    x=2
   
    
add_no()

print(x)


2


In [78]:

x="awesome"
def myfunc():
    print("python is " + x)
myfunc()    
        

python is awesome


In [83]:
x="magic"
def myfunc():
    x="python"
    print("python is " + x)
myfunc()    
print("python is " + x) 

python is python
python is magic


In [86]:
x="rakesh"
def myfunc():
    global x
    x="awesome"
myfunc()
print("python is " + x)

python is awesome


In [3]:
x="john"
print(x)

john


In [2]:
age=7
print(age)

7


In [5]:
age=7
print(age)

7


In [1]:
x,y,z="rakesh","suresh","srilatha"
print(x,y,z)

rakesh suresh srilatha


In [2]:
x=y=z="suresh"
print(x,y,z)

suresh suresh suresh


In [4]:
x=6
y=8
z=(x+y)
print(z)

14


In [5]:
x="srilatha"
print("rakesh son is " + x)

rakesh son is srilatha


In [7]:
x="rupesh"
y="rajesh"
z=x+y
print(z)

rupeshrajesh


In [9]:
x="ramesh"
def rakesh():
    print("suresh son is " + x)
rakesh()    

suresh son is ramesh


In [6]:
x=2
def add_no(x):
    print("" + x)
add_no(x)    

TypeError: can only concatenate str (not "int") to str

In [21]:
x="mohanlal"
def myfunc():
    x="srilatha"
    print("mohanlal daughter is " + x)
myfunc()
print("srilatha daughter is " + x)

mohanlal daughter is srilatha
srilatha daughter is mohanlal


In [2]:
x="rakesh"
def myfunc():
    print("python is "+x)
myfunc()



python is rakesh


In [50]:
x=1
y=4758588488
z=68877
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'int'>
<class 'int'>


In [52]:
x=6.9
y=3.9
z=55.9
print(type(x))
print(type(y))
print(type(z))

<class 'float'>
<class 'float'>
<class 'float'>


In [54]:
x=456e6
y=76e4
z=879e4
print(type(x))
print(type(y))
print(type(z))

<class 'float'>
<class 'float'>
<class 'float'>


In [61]:
x=4j+3
y=6+4j
z=4+6jprint(type(x))
print(type(y))
print(type(z))
print(type(x))
print(type(y))
print(type(print(type(x))
print(type(y))
print(type(z))z))

<class 'complex'>
<class 'complex'>
<class 'complex'>


In [70]:
a=2
b=7
c=6j
x=float(a)
y=int(b)
z=complex(c)
print(a)
print(b)
print(c)
print(type(a))
print(type(b))
print(type(c))


2
7
6j
<class 'int'>
<class 'int'>
<class 'complex'>


In [71]:
x=6.6
y=6
z=9j
print(type(x))
print(type(y))
print(type(z))

<class 'float'>
<class 'int'>
<class 'complex'>


In [4]:
x=8
y=6.9
z=98j
a=float(x)
b=int(y)
c=complex(z)
print(a)
print(b)
print(c)
print(type(x))
print(type(y))
print(type(z))



8.0
6
98j
<class 'int'>
<class 'float'>
<class 'complex'>


In [6]:
x="rakesh"
def myfunc():
    x="suresh"
    print("my dad number starts with " + x)
myfunc()
print("my dad number starts with " + x)

my dad number starts with suresh
my dad number starts with rakesh


In [10]:
x=2
y=5.8
z=8j
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'float'>
<class 'complex'>


In [13]:
x=float(x)
y=int(y)
z=complex(z)
print(x)
print(y)
print(z)

2.0
5
8j


In [24]:
x="suresh"
def rakesh():
    x="raju"
    print("my age is " + x)
rakesh()
print("my age is " + x)

my age is raju
my age is suresh


In [25]:
x="Hello World"
print(x)

Hello World


In [1]:
x="3"
print(type(x))

<class 'str'>


In [2]:
#casting
y=int("3")
print(type(y))

<class 'int'>


In [6]:
x=int(float("3.0"))
type(x)
x

3

In [8]:
z='''ram,
rahim,
raj'''
print(z)

ram,
rahim,
raj


In [12]:
a = "Hello, World!"
print(a[12])

!


In [13]:
b = "Hello, World!"
print(b[-6:-2])

Worl


In [14]:
len(b)

13

In [15]:
x=["apple,banana,grape"]
print(type(x))

<class 'list'>


In [16]:
x

['apple,banana,grape']

In [21]:
 x=["apple","banana","grape"]
print(type(x))


<class 'list'>


In [22]:
#tuple
x=("apple","banana","grape")
print(type(x))

<class 'tuple'>


In [23]:
#range
x=range(6)
x

range(0, 6)

In [28]:
#dict
x={"name" :"john", "age" :54}
x

{'name': 'john', 'age': 54}

In [30]:
#set
x={"rakesh","rajesh","ramu"}
x
print(type(x))

<class 'set'>


In [32]:
#frozen set
x=({"rakesh","rajesh","rupesh"})
print(type(x))

<class 'set'>


In [35]:
#bool
x=True
x

True

In [36]:
#bytes
x=b"hello"
x

b'hello'

In [37]:
 #bytearray
x=bytearray(7)
x

bytearray(b'\x00\x00\x00\x00\x00\x00\x00')

In [38]:
#memory view 
x=memoryview(bytes(5))
x

In [41]:
#casting
x=int(1)
y=int(4.0)
z=int("5")
print(type(x))
print(type(y))
print(type(z))

<class 'int'>
<class 'int'>
<class 'int'>


In [42]:
a="s1"
type(a)

str

In [43]:
w=float(1)
x=float(2.8)
y=float("5")
z=float("4.8")
print(type(w))
print(type(x))
print(type(y))
print(type(z))

<class 'float'>
<class 'float'>
<class 'float'>
<class 'float'>


In [44]:
x=str("6")
y=str(4)
z=str("9")
print(type(x))
print(type(y))
print(type(z))

<class 'str'>
<class 'str'>
<class 'str'>


In [46]:
#python string
print("hello world")
print('hello world')

hello world
hello world


In [47]:
a="hello world"
print(a)

hello world


In [51]:
a="""rakeh
rupesh
ramesh"""
print(a)

rakeh
rupesh
ramesh


In [55]:
#strings are arrays
a="Hello world"
print(a[6])

w


In [68]:
x="hello, world!"
print(x[1:6])

ello,


In [64]:
x="hello world!"
print(x[-9:-6])

lo 


In [72]:
b = "Hello, World!"
print(b[-4:-1])

rld


In [73]:
b="rakesh kumar"
print(b[-7:-3])

h ku


In [75]:
z="sandeep kumar"
print(z[-4:-2])

um


In [77]:
x="rakesh, roshan"
print(x[1:6])

akesh


In [78]:
y="praneeth devil"
print(y[1:10])

raneeth d


In [81]:
w="jayanth goud"
print(w[-5:-3])

 g


In [82]:
x="rakesh"
print(len(x))

6


In [2]:
#list
x=["banana","mango","apple"]
print(type(x))

<class 'list'>


In [6]:
#tuple 
x=("banana","mango","pineapple")
print(type(x))

<class 'tuple'>


In [7]:
#range
x=range(10)
x

range(0, 10)

In [11]:
#dictionary
x={"name":"rakesh","age":65}
x
print(type(x))

<class 'dict'>


In [12]:
#set
x={"sandeep","venkatesh","haripriya"}
x
print(type(x))

<class 'set'>


In [14]:
#frozenset
x=({"rakesh","rajesh","rupesh"})
x
print(type(x))

<class 'set'>


In [17]:
#boolean
x=False
x

False

In [19]:
x=b"hello world"
x
print(type(x))

<class 'bytes'>


In [21]:
X=bytearray(9)
x
print(type(x))

<class 'bytes'>


In [23]:
x=memoryview(bytes(5))
x

In [6]:
x=int(5)
y=int(4.8)
z=int("6")
x
y
z

6

In [9]:
x=float("3")
y=float(4.0)
z=float(4)
print(type(x))

<class 'float'>


In [14]:
x=str("9")
y=str(45)
z=str("76")
print(type(x))
print(type(z))

<class 'str'>
<class 'str'>


In [4]:
a="""rakesh\n rajesh\n rupesh\nharish
raghu\n ravi\nranjan\n ramesh\n raju
ravish\n ramu\n rahul """
a

'rakesh\n rajesh\n rupesh\nharish\nraghu\n ravi\nranjan\n ramesh\n raju\nravish\n ramu\n rahul '

In [17]:
a="raghuram"
print(a[3])

h


In [20]:
a="rajeev"
print(len(a))

6


In [21]:
a="rakesh roshan"
print(a[1:8])

akesh r


In [22]:
b="gulshan kumar"
print(b[-5:-1])

kuma


In [10]:
x="john"
y=str("5")
print(x)
print(type(y))

john
<class 'str'>


In [3]:
x="""rakesh is good boy
   nikhil is good boy"""
print(x)

rakesh is good boy
   nikhil is good boy


In [7]:
a="hellboy superman"
print(a[8])

s


In [7]:
a=" rakesh roshan "
print(a.strip())

rakesh roshan


In [9]:
b=" hello hello "
print(b.strip())

hello hello


In [10]:
a="makhdoom"
print(a.upper())

MAKHDOOM


In [11]:
c="raju ramesh both are friends"
print(c.upper())

RAJU RAMESH BOTH ARE FRIENDS


In [16]:
z="GAYATRI WATERFALLS"
print(z.lower())

gayatri waterfalls


In [19]:
x="srilatha suresh"
print(x.replace("s","j"))

jrilatha jurejh


In [23]:
a="hello world!"
print(a.split("d"))

['hello worl', '!']


In [24]:
a="shiv charan"
print(a.split("a"))

['shiv ch', 'r', 'n']


In [26]:
b="scooby dooby do"
print(b.split("o"))

['sc', '', 'by d', '', 'by d', '']


In [8]:
z="superman batman"
print(z.split("a"))

['superm', 'n b', 'tm', 'n']


In [32]:
txt="rakesh is the good boy in world"
x="where" in txt
print(x)

False


In [37]:
txt="water is used in the underground water"
x="tape" in txt
print(x)

False


In [39]:
x="ravi"
z="raj"
y=x+z
print(y)

raviraj


In [40]:
z="american"
x="club"
y=z+x
print(y)

americanclub


In [12]:
a="hello"
b="world"
c=a+" "+b
print(c)

hello world


In [46]:
b="rakesh"
c="roshan"
d=b+" "+c
print(d)

rakesh roshan


In [48]:
age=43
txt="my name is john,and i am {}"
print(txt.format(age))

my name is john,and i am 43


In [49]:
rule=65
txt="my rule number is {}"
print(txt.format(rule))

my rule number is 65


In [218]:
circle=54
txt="my favourite circle is {}".format(circle)
print(txt)

my favourite circle is 54


In [52]:
lucky=89
txt="my lucky number is {}"
print(txt.format(lucky))

my lucky number is 89


In [55]:
quantity=8
itemno=98
price=876
myorder="i want {} piece of item {} in dollars {}"
print(myorder.format(quantity,itemno,price))

i want 8 piece of item 98 in dollars 876


In [58]:
chocolates=8
biscuits=5
icecreams=65
my_items="chocolates {} biscuits {} icecreams {}"
print(my_items.format(chocolates,biscuits,icecreams))

chocolates 8 biscuits 5 icecreams 65


In [59]:
chocolates=8
biscuits=5
icecreams=65
my_items="chocolates {2} biscuits {0} icecreams {1}"
print(my_items.format(biscuits,icecreams,chocolates))

chocolates 8 biscuits 5 icecreams 65


In [62]:
greenchilles=8
redchilles=7
apples=4
my_things="greenchilles {} redchilles {} apples {}"
print(my_things.format(greenchilles,redchilles,apples))

greenchilles 8 redchilles 7 apples 4


In [12]:
#capitalize() 
x="rakesh is good boy"
x.capitalize()


'Rakesh is good boy'

In [13]:
x="rakesh is good boy"
x.upper()

'RAKESH IS GOOD BOY'

In [28]:
z="murali krishna is a teacher"
z.upper()
#z.lower()
#z.capitalize()

'MURALI KRISHNA IS A TEACHER'

In [29]:
txt="satya vamshi is good singer"
x=txt.capitalize()
print(x)

Satya vamshi is good singer


In [30]:
d="rakesh is good boy"
x=d.capitalize()
print(x)

Rakesh is good boy


In [34]:
r="rakesh is good Boy"
r.casefold()

'rakesh is good boy'

In [40]:
r="satya goud"
r.center(20)

'     satya goud     '

In [22]:
txt="satya vamshi"
f=txt.center(100)
print(f)

                                            satya vamshi                                            


In [50]:
txt="i love india,india is my country"
x=txt.count("india")
print(x)

2


In [27]:
a="my favourite food is biriyani,biriyani is my favourite food"
a.count("favourite")

2

In [57]:
txt="rakesh is my good"
d=txt.encode()
print(d)

b'rakesh is my good'


In [69]:
txt="hockey is my favourite game,cricket is my world."
x=txt.endswith(".")
print(x)

True


In [71]:
txt="rakesh is my name,"
x=txt.endswith(".")
print(x)

False


In [73]:
txt=""
c=txt.expandtabs(9)
print(c)


hello world


In [75]:
txt = "H\te\tl\tl\to"
print(txt)

H	e	l	l	o


In [76]:
name="R\takesh"
print(name)

R	akesh


In [80]:
txt="r\ta\tkesh"
d=txt.expandtabs()
print(d)

r       a       kesh


In [85]:
name="w\th\ti\tt\tifield"
r=name.expandtabs(6)
print(r)

w     h     i     t     ifield


In [87]:
name="r\ta\tm\te\tsh"
d=name.expandtabs()
print(d)

r       a       m       e       sh


In [88]:
name="r\ta\tm\te\tsh"
d=name.expandtabs(2)
print(d)

r a m e sh


In [89]:
name="r\ta\tm\te\tsh"
d=name.expandtabs(10)
print(d)

r         a         m         e         sh


In [90]:
name="r\ta\tm\te\tsh"
d=name.expandtabs(20)
print(d)

r                   a                   m                   e                   sh


In [92]:
name="r\ta\tm\te\tsh"
d=name.expandtabs(10)
print(d)

r         a         m         e         sh


In [93]:
txt="my dad is my hero"
u=txt.find("hero")
print(u)

13


In [95]:
txt="hockey is our national game"
a=txt.find("our")
print(a)

10


In [96]:
txt="letter of the mam"
c=txt.find("t")
print(c)

2


In [106]:
txt="array is my favourite"
a=txt.find("y")
print(a)

4


In [1]:
txt = "My name is Ståle"
print(txt)

My name is Ståle


In [9]:
txt= "My name is Ståle"
print(txt.encode(encoding="ascii",errors="backslashreplace"))
print(txt.encode(encoding="ascii",errors="ignore"))
print(txt.encode(encoding="ascii",errors="namereplace"))
print(txt.encode(encoding="ascii",errors="replace"))


b'My name is St\\xe5le'
b'My name is Stle'
b'My name is St\\N{LATIN SMALL LETTER A WITH RING ABOVE}le'
b'My name is St?le'


In [10]:
print(txt.encode(encoding="ascii",errors="xmlcharrefreplace"))


b'My name is St&#229;le'


In [11]:
print(txt.encode(encoding="ascii",errors="strict"))


UnicodeEncodeError: 'ascii' codec can't encode character '\xe5' in position 13: ordinal not in range(128)

In [13]:
txt = "For only {price:.3f} dollars!"
print(txt.format(price = 50))


For only 50.000 dollars!


In [20]:
txt="vanila chocholate if for {price:.9f} euros!"
print(txt.format(price = 80))

vanila chocholate if for 80.000000000 euros!


In [25]:
txt="this dresss is for {price:.4f} rupees!"
print(txt.format(price=56))

this dresss is for 56.0000 rupees!


In [27]:
txt="this toy is for {price:.6f} dollars !"
print(txt.format(price=76))

this toy is for 76.000000 dollars !


In [28]:
txt="this thing is available for {price:.6f} dollars!"
print(txt.format(price=56))

this thing is available for 56.000000 dollars!


In [29]:
txt1="my shopename is {fname},my shop number is {number}".format(fname="shruthi", number=56)
txt1

'my shopename is shruthi,my shop number is 56'

In [39]:
txt1= "My name is {fname}, I'am {age}".format(fname = "John", age = 36)
txt2= "My name is {0}, I'am {1}".format("John",36)
txt3 = "My name is {}, I'am {}".format("John",36)


In [40]:
txt1 = "My name is {fname}, I'am {age}".format(fname = "John", age = 36)

In [41]:
txt1

"My name is John, I'am 36"

In [42]:
txt2

"My name is John, I'am 36"

In [43]:
txt3

"My name is John, I'am 36"

In [2]:
x="hello world!"
print(x.split("w"))

['hello ', 'orld!']


In [13]:
shop=45
txt="my shop is in nizambad,and shop number is {}"
print(txt.format(shop))

my shop is in nizambad,and shop number is 45


In [15]:
greengram=8
redgram=8
bengalgram=9
myitems="greengram {} redgram {} bengalgram {}"
print(myitems.format(greengram,redgram,bengalgram))

greengram 8 redgram 8 bengalgram 9


In [19]:
coconuts=67
apples=87
mangoes=54
mythings="coconuts {2} apples {0} mangoes {1}"
print(mythings.format(coconuts,apples,mangoes))

coconuts 54 apples 67 mangoes 87


In [24]:
txt="king khan"
d=txt.capitalize()
print(d)

King khan


In [25]:
txt=" 78 is my shope number "
f=txt.capitalize()
print(f)

 78 is my shope number 


In [26]:
txt=" MY NAME IS RAKESH ROSHAN "
d=txt.casefold()
print(d)

 my name is rakesh roshan 


In [29]:
txt="rakesh kumar"
d=txt.center(20)
print(d)

    rakesh kumar    


In [38]:
txt="raju ramesh krishnamurty rahul are friends"
u=txt.center(10)
print(u)

raju ramesh krishnamurty rahul are friends


In [32]:
txt="rakesh"
c=txt.center(100,"9")
print(c)

99999999999999999999999999999999999999999999999rakesh99999999999999999999999999999999999999999999999


In [42]:
txt="rakesh"
r=txt.count("e")
print(r)

1


In [61]:
txt="roshan vakesh yadav,rahul rakesh yadav"
d=txt.count("yadav")
print(d)

2


In [81]:
txt="hockey is national game, hockey is my favourite"
d=txt.count("hockey", 0, 50)
print(d)

2


In [99]:
txt = "I love apples, apple are my favorite fruit"

x = txt.count("apple", 0, 20)

print(x)

2


In [97]:
txt="chinese good is my favourite food,and it is prepaid by chinese people"
g=txt.count("chinese", 0,62)
print(g)

2


In [104]:
txt="manish is my favourite friend6"
d=txt.endswith("9")
print(d)

False


In [108]:
txt="tr\t1a\t2kesh"
s=txt.expandtabs()
print(s)

tr      1a      2kesh


In [1]:
txt="ramesh ravi"
a=txt.find("ravi")
print(a)

7


In [4]:
txt="the dress is for {price:.9f} dollars!"
print(txt.format(price=67))

the dress is for 67.000000000 dollars!


In [7]:
txt1="my shope name is {fname}, my shope number is {number}".format(fname= "rakesh",number=3)
txt2="my shope name is {0}, my shope number is {1}".format(fname= "rakesh",number=3)
txt3="my shope name is {}, my shope number is {},".format(fname= "rakesh",number=3)


IndexError: tuple index out of range

In [18]:
txt1="my name is {fname}, and i'm {age}".format(fname="rakesh", age=23)
txt2="my name is {0}, and i'm {1}".format("rakesh", 23)
txt3="my name is {}, and i'm {}".format("rakesh", 23)

In [35]:
txt1="my shopename {fname}, my shope number {number}".format(fname="rakesh",number=43)
txt2="my shopename {0}, my shope number {1}".format("rakesh",43)
txt3="my shopename {}, my shope number {}".format("rakesh",43)



In [36]:
txt1

'my shopename rakesh, my shope number 43'

In [27]:
txt1

'my shopename rakesh, my shope (number)'

In [29]:
txt1

'my shopename rakesh, my shope (43)'

In [30]:
txt2

'my shopename rakesh, my shope number (1)'

In [31]:
txt3

'my shopename rakesh, my shope number ()'

In [35]:
txt="i have {:>9}biscits."
print(txt.format(500))

i have       500biscits.


In [53]:
txt="we use {:^7} cashew nuts."
print(txt.format(43))

we use   43    cashew nuts.


In [64]:
txt="the season of summer is {:=2} degrees celcius"
print(txt.format(+34))

the season of summer is 34 degrees celcius


In [67]:
txt="the temperature is between {:+} and {:+}degree celcius"
print(txt.format(-8,9))

the temperature is between +8 and +9degree celcius


In [69]:
txt="the summer is so hot {:-},and {:-} degree celcius"
print(txt.format(9,-6))

the summer is so hot 9,and -6 degree celcius


In [83]:
txt="the summer is so hot {: },and {: } degree celcius"
print(txt.format(-8, 8))

the summer is so hot -8,and  8 degree celcius


In [84]:
txt="my shirts is {:,} cost"
print(txt.format(13000))

my shirts is 13,000 cost


In [86]:
txt="my car is about {:,}"
print(txt.format(200000))

my car is about 200,000


In [89]:
txt="our univers is of {:_}"
print(txt.format(130000))

our univers is of 130_000


In [105]:
txt="my shirt is of {0} is {0:b}"
print(txt.format(30))

my shirt is of 30 is 11110


In [106]:
txt="rakesh is of {0} is {0:b}"
print(txt.format(87))

rakesh is of 87 is 1010111


In [113]:
txt="the chicken {:d} rate"
print(txt.format(0b10001))

the chicken 17 rate


In [115]:
txt="the launch is {:d} not"
print(txt.format(0b10011))

the launch is 19 not


In [120]:
txt="my name is {:e} rakesh"
print(txt.format(4))

my name is 4.000000e+00 rakesh


In [121]:
txt="my name is {:E} king khan"
print(txt.format(4))

my name is 4.000000E+00 king khan


In [140]:
x=float('inf')
txt="my currency is {:f} dollars !"
print(txt.format(x))
txt="my euros is {:F} dollars !"
print(txt.format(x))


my currency is inf dollars !
my euros is INF dollars !


In [152]:
txt = "The octal version of {0} is {0:d}"

print(txt.format(30))


The octal version of 30 is 30


In [147]:
txt="The octal version of {0} is {0:f}"
print(txt.format(43))

The octal version of 43 is 43.000000


In [153]:
txt="you scored {:%}"
print(txt.format(0.45))

you scored 45.000000%


In [158]:
txt="you scored {:.0%}"
print(txt.format(0.45))

you scored 45%


In [168]:
txt="your marks {:%}"
print(txt.format(0.98))

your marks 98.000000%


In [163]:
txt="your marks {:.0%}"
print(txt.format(0.98))

your marks 98%


In [169]:
txt="rakesh is my name"
print(txt.index("my"))

10


In [171]:
txt="hello world"
print(txt.index("world"))

6


In [183]:
txt="23"
x=txt.isalnum()
print(x)

True


In [185]:
txt="rakesh^34"
d=txt.isalnum()
print(d)

False


In [188]:
txt="rakeshx"
x=txt.isalpha()
print(x)

True


In [210]:
txt="67tr"
x=txt.isdecimal()
print(x)

False


In [36]:
age=23
x="rakesh is my name, and my age {}"
print(x.format(age))


rakesh is my name, and my age 23


In [255]:
import numpy as N
data = N.zeros((10,3), dtype='float')
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [271]:
data[:,0]=N.arange(2,22,2)
data

array([[ 2.,  0.,  0.],
       [ 4.,  0.,  0.],
       [ 6.,  0.,  0.],
       [ 8.,  0.,  0.],
       [10.,  0.,  0.],
       [12.,  0.,  0.],
       [14.,  0.,  0.],
       [16.,  0.,  0.],
       [18.,  0.,  0.],
       [20.,  0.,  0.]])

In [243]:
data


array([[0., 0.],
       [1., 0.],
       [2., 0.],
       [3., 0.],
       [4., 0.]])

In [246]:
data[:,1]=data[:,0]**2.0

In [247]:
data

array([[ 0.,  0.],
       [ 1.,  1.],
       [ 2.,  4.],
       [ 3.,  9.],
       [ 4., 16.]])

In [248]:
data

array([[ 0.,  0.],
       [ 1.,  1.],
       [ 2.,  4.],
       [ 3.,  9.],
       [ 4., 16.]])

In [37]:
import numpy as np
data1=np.zeros((10,3), dtype='float'))
data1


SyntaxError: invalid syntax (<ipython-input-37-4af04aff03ea>, line 2)

In [272]:
data[:,1]=N.(3,33,3)

data

array([[ 2.,  3.,  0.],
       [ 4.,  6.,  0.],
       [ 6.,  9.,  0.],
       [ 8., 12.,  0.],
       [10., 15.,  0.],
       [12., 18.,  0.],
       [14., 21.,  0.],
       [16., 24.,  0.],
       [18., 27.,  0.],
       [20., 30.,  0.]])

In [286]:
data[:,2]=N.arange(1,15,2)
data

ValueError: could not broadcast input array from shape (7) into shape (10)

In [287]:
data[:,2]=N.arange(4,44,4)
data

array([[ 2.,  3.,  4.],
       [ 4.,  6.,  8.],
       [ 6.,  9., 12.],
       [ 8., 12., 16.],
       [10., 15., 20.],
       [12., 18., 24.],
       [14., 21., 28.],
       [16., 24., 32.],
       [18., 27., 36.],
       [20., 30., 40.]])

In [289]:
#for even numbers
data[:,0]=N.arange(2,22,2)
data

array([[ 2.,  3.,  4.],
       [ 4.,  6.,  8.],
       [ 6.,  9., 12.],
       [ 8., 12., 16.],
       [10., 15., 20.],
       [12., 18., 24.],
       [14., 21., 28.],
       [16., 24., 32.],
       [18., 27., 36.],
       [20., 30., 40.]])

In [292]:
data1=np.zeros((10,3), dtype='float')
data1

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [293]:
data1[:,0]=N.arange(2,22,2)
data1

array([[ 2.,  0.,  0.],
       [ 4.,  0.,  0.],
       [ 6.,  0.,  0.],
       [ 8.,  0.,  0.],
       [10.,  0.,  0.],
       [12.,  0.,  0.],
       [14.,  0.,  0.],
       [16.,  0.,  0.],
       [18.,  0.,  0.],
       [20.,  0.,  0.]])

In [294]:
data1[:,1] = data[:,0]-1
data1

array([[ 2.,  1.,  0.],
       [ 4.,  3.,  0.],
       [ 6.,  5.,  0.],
       [ 8.,  7.,  0.],
       [10.,  9.,  0.],
       [12., 11.,  0.],
       [14., 13.,  0.],
       [16., 15.,  0.],
       [18., 17.,  0.],
       [20., 19.,  0.]])

In [302]:
# Initialize a list
primes = []
for possiblePrime in range(2, 30):
  # Assume number is prime until shown it is not. 
    isPrime = True
    for num in range(2, possiblePrime):
        if possiblePrime % num == 0:
            isPrime = False
      
    if isPrime:
        primes.append(possiblePrime)

In [305]:
data1[:,2] = primes
data1

array([[ 2.,  1.,  2.],
       [ 4.,  3.,  3.],
       [ 6.,  5.,  5.],
       [ 8.,  7.,  7.],
       [10.,  9., 11.],
       [12., 11., 13.],
       [14., 13., 17.],
       [16., 15., 19.],
       [18., 17., 23.],
       [20., 19., 29.]])

In [4]:
data2=np.zeros((10,3), dtype='float')
data2

NameError: name 'np' is not defined

In [5]:
import numpy as N
data = N.zeros((10,3), dtype='float')
data

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [18]:
a=N.array(N.arange(29).reshape(0,1))
a


ValueError: cannot reshape array of size 29 into shape (0,1)

In [2]:
txt="6008"
d=txt.isdigit()
print(d)

True


In [12]:
txt="rakesh"
d=txt.isidentifier()
print(d)

True


In [42]:
txt=" rakesh"
d=txt.isidentifier()
print(d)

False


In [14]:
a="rakesh 12"
b="135haneeesh"
c="dumb"
d="cat123"
print(a.isidentifier())
print(b.isidentifier())
print(c.isidentifier())
print(d.isidentifier())

False
False
True
True


In [19]:
a="HELLO WORLD"
b="myname ispeter"
print(a.islower())
print(b.islower())

False
True


In [38]:
txt="hello im n.rakesh are you g?"
print(txt.isprintable())

True


In [41]:
txt=" "
print(txt.isspace())

True


In [50]:
txt="12 Rakesh"
print(txt.istitle())

True


In [56]:
txt="123RAKESH ROSHAN"
print(txt.isupper())

True


In [69]:
a="my name is"
d=a.ljust(0)
print(d,"rakesh")

my name is rakesh


In [82]:
txt="rakesh"
print(txt.ljust(40, "f"))

rakeshffffffffffffffffffffffffffffffffff


In [83]:
txt="king khan"
print(txt.ljust(80,"n"))

king khannnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn


In [84]:
txt="HELLO MY FRIENDS"
print(txt.lower())

hello my friends


In [85]:
txt="i eat lot of chinese food"
print(txt.partition("chinese"))

('i eat lot of ', 'chinese', ' food')


In [3]:
txt="my name is    rakesh     roshan"
print(txt.partition("is"))

('my name ', 'is', '    rakesh     roshan')


In [100]:
txt="my name is rakesh"
print(txt.replace("rakesh","nayak"))

my name is nayak


In [103]:
txt="my name is rakesh rakesh rakesh rakesh and roshan roshan"
print(txt.replace("rakesh","ramesh"))

my name is ramesh ramesh ramesh ramesh and roshan roshan


In [106]:
txt="rakesh is rakesh"
print(txt.rfind("a"))

11


In [10]:
a=[1,2,3,4,5,6]
print(a[:2])

[1, 2]


In [14]:
a=[1,2,3,4]
b=[5,6,7,8]
c=zip(a,b)
print(c)

In [17]:
a=[1,2,3,4,5,6]
print(a[2:5])

[3, 4, 5]


In [21]:
a=[1,2,3,4,5,6]
a.append("rakesh")
print(a)

[1, 2, 3, 4, 5, 6, 'rakesh']


In [27]:
a=[3,4,5,6,7]
print(a[1])=99
a

SyntaxError: can't assign to function call (<ipython-input-27-1931334caaa9>, line 2)

In [41]:
a="my name is rakesh"
print(a.find("rakesh"))

11


In [53]:
import numpy as np
a=np.arange(10, dtype="float")
a.shape=(5,2) 
a

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [71]:
a=np.arange(25,dtype="float")
a.shape=(5,5)

In [72]:
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [73]:
b=a**2

In [74]:
b

array([[  0.,   1.,   4.,   9.,  16.],
       [ 25.,  36.,  49.,  64.,  81.],
       [100., 121., 144., 169., 196.],
       [225., 256., 289., 324., 361.],
       [400., 441., 484., 529., 576.]])

In [75]:
b=np.arange(9,dtype="float")

In [76]:
b

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [82]:
print(b[1:3])

[1. 2.]


In [86]:
rakesh={"raju":12345,"ravi":678910,"rahu":1112131415}
rakesh

{'raju': 12345, 'ravi': 678910, 'rahu': 1112131415}

In [87]:
len(rakesh)

3

In [97]:
a=np.arange(25,dtype="float")
a.shape=(5,5)
a

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

In [102]:
print(a[3,1])

16.0


In [103]:
a=np.arange(10,dtype="float")
a.shape=(2,5)
a

array([[0., 1., 2., 3., 4.],
       [5., 6., 7., 8., 9.]])

In [111]:
print(a[:,2])

[2. 7.]


In [124]:
a=float(input("enter the number:"))
if a<12:
    print("this is positive number")
else:
    print("this is negative number")

enter the number:13
this is negative number


In [3]:
a = float(input('Please enter a positive number: '))
if a < 0:
    print('That is a negative number')
    print('That is not what I asked for')
elif a> 0:
    print('Thank you')    
    print('That is a positive number')
else:
     print('That looks like zero to me')         
 

Please enter a positive number: -1
That is a negative number
That is not what I asked for


In [3]:
b=float(input("enter the number:"))
if b<0:
    print("this is what not i expected")
elif b>0:
    print("this is i expected")
else:
    print("it might be some other")

enter the number:0
it might be some other


In [9]:
x=-1
while x<=0 or x>9: 
    x = float(input()) 
    print('Thank you. That number is fine.') 
    

9
Thank you. That number is fine.


In [12]:
prompt="enter the number please:"
x=-2
while(x<5 or x>9):
    x=float(input(prompt))
    print("Thank you.That number is fine.")

enter the number please:10
Thank you.That number is fine.
enter the number please:7
Thank you.That number is fine.


In [1]:
a="enter the number please:"
x=-5
while(x<4 or x>13):
    x=float(input(a))
    print("you have entered number is fine")
    

enter the number please:3
you have entered number is fine
enter the number please:14
you have entered number is fine
enter the number please:2
you have entered number is fine
enter the number please:5
you have entered number is fine


In [7]:
cheeseList = ['Wensleydale', 'Stilton', 'Danish Blue', 'Red Leicester', 'Brie']
for cheese in range(0:
    print("the cheesename is"cheeseList[cheese],"?")

SyntaxError: invalid syntax (<ipython-input-7-10a7f9f2a6fe>, line 3)